### ISSUE TITLE
readlink: illegal option -- f on Mac

### ISSUE THREAD

**Issue by zopyx** [transpect/xlsx2html-frontend#1]
```
Suxmac:xlsx2html-frontend ajung$ ./xlsxconv sample.xlsx
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

**Comment by gimsieke** [comment]
I thought I eliminated them all, but one occurrence of `readlink -f` slipped through. I Published a new release: https://github.com/transpect/xlsx2html-frontend/releases/tag/0.9
